services:
  fabric:
    build: .
    container_name: fabric-server
    ports:
      - "25565:25565"
      - "25575:25575"
      - "24454:24454/udp"
    volumes:
      - ./data:/data
      - ./.env:/data/.env
    restart: unless-stopped
